name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    branches: [ main ]
  pull_request:
    branches: [ master ]
    branches: [ main ]

jobs:
  build-java:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build
